package cn.fuyoushuo.domain.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.fuyoushuo.domain.entity.BookMark;
import cn.fuyoushuo.domain.entity.HistoryItem;
import cn.fuyoushuo.domain.entity.StaticData;
import cn.fuyoushuo.domain.entity.DownloadTask;
import cn.fuyoushuo.domain.entity.UserTrack;

import cn.fuyoushuo.domain.greendao.BookMarkDao;
import cn.fuyoushuo.domain.greendao.HistoryItemDao;
import cn.fuyoushuo.domain.greendao.StaticDataDao;
import cn.fuyoushuo.domain.greendao.DownloadTaskDao;
import cn.fuyoushuo.domain.greendao.UserTrackDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookMarkDaoConfig;
    private final DaoConfig historyItemDaoConfig;
    private final DaoConfig staticDataDaoConfig;
    private final DaoConfig downloadTaskDaoConfig;
    private final DaoConfig userTrackDaoConfig;

    private final BookMarkDao bookMarkDao;
    private final HistoryItemDao historyItemDao;
    private final StaticDataDao staticDataDao;
    private final DownloadTaskDao downloadTaskDao;
    private final UserTrackDao userTrackDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookMarkDaoConfig = daoConfigMap.get(BookMarkDao.class).clone();
        bookMarkDaoConfig.initIdentityScope(type);

        historyItemDaoConfig = daoConfigMap.get(HistoryItemDao.class).clone();
        historyItemDaoConfig.initIdentityScope(type);

        staticDataDaoConfig = daoConfigMap.get(StaticDataDao.class).clone();
        staticDataDaoConfig.initIdentityScope(type);

        downloadTaskDaoConfig = daoConfigMap.get(DownloadTaskDao.class).clone();
        downloadTaskDaoConfig.initIdentityScope(type);

        userTrackDaoConfig = daoConfigMap.get(UserTrackDao.class).clone();
        userTrackDaoConfig.initIdentityScope(type);

        bookMarkDao = new BookMarkDao(bookMarkDaoConfig, this);
        historyItemDao = new HistoryItemDao(historyItemDaoConfig, this);
        staticDataDao = new StaticDataDao(staticDataDaoConfig, this);
        downloadTaskDao = new DownloadTaskDao(downloadTaskDaoConfig, this);
        userTrackDao = new UserTrackDao(userTrackDaoConfig, this);

        registerDao(BookMark.class, bookMarkDao);
        registerDao(HistoryItem.class, historyItemDao);
        registerDao(StaticData.class, staticDataDao);
        registerDao(DownloadTask.class, downloadTaskDao);
        registerDao(UserTrack.class, userTrackDao);
    }
    
    public void clear() {
        bookMarkDaoConfig.clearIdentityScope();
        historyItemDaoConfig.clearIdentityScope();
        staticDataDaoConfig.clearIdentityScope();
        downloadTaskDaoConfig.clearIdentityScope();
        userTrackDaoConfig.clearIdentityScope();
    }

    public BookMarkDao getBookMarkDao() {
        return bookMarkDao;
    }

    public HistoryItemDao getHistoryItemDao() {
        return historyItemDao;
    }

    public StaticDataDao getStaticDataDao() {
        return staticDataDao;
    }

    public DownloadTaskDao getDownloadTaskDao() {
        return downloadTaskDao;
    }

    public UserTrackDao getUserTrackDao() {
        return userTrackDao;
    }

}
